name: 泛微-EOffice-v9.5-config泄露
description: >
  泄露账户密码
alwaysExecute: false
matchCount: 1
rules:
  - method: GET
    path: /building/config/config.ini
    follow_redirects: false
    expression:
      status: 200
      body_all:
        - "building"
        - "password"  